# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada7804cc3fe924d14b1362f7485488051f8b09376d5c51c376aa8c7c5129a597390db8a3819ee540c57f0c8be4dc649812108d240b7b1b50fc8130f766f56c4

test:
  secret_key_base: 7f7e8a5ea442086e365fc484ad69956087bf280ca0a014017a3bbcf6027da14e5082ad85b4a7d9aecf2c3ae4582e621f6471a28f7466cfccc1613a3cd2ac1560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
